title: Binghao Wang's Homepage
page-top-title: Binghao Wang
top-section-bg-text: Artificial Intelligence
home-subtitle: Binghao Wang&ensp;|&ensp;王柄皓
copyright-text: '&copy; Binghao Wang 2025-2026. All Rights Reserved.'
