title: Zhicheng Tong's Homepage
page-top-title: Zhicheng Tong
top-section-bg-text: Mathematics: Dynamical Systems
home-subtitle: Zhicheng Tong&ensp;|&ensp;佟志成
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
